module.exports = class Data1775307076452 {
    name = 'Data1775307076452'

    async up(db) {
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "symbol" text NOT NULL, "name" text NOT NULL, "decimals" integer NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "v2_pool" ("id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE, "dex" character varying(21) NOT NULL, "token0_id" character varying, "token1_id" character varying, CONSTRAINT "PK_df2b40d852cbb5343a8a1e16806" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_24bc7b055de2e69490450f40b2" ON "v2_pool" ("token0_id") `)
        await db.query(`CREATE INDEX "IDX_137cf1f2b23e63006ec88508af" ON "v2_pool" ("token1_id") `)
        await db.query(`CREATE TABLE "v2_pool_snapshot" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "after_tx_id" text, "priority_inclusion_fee_per_unit" numeric, "index" integer, "reserve0" numeric NOT NULL, "reserve1" numeric NOT NULL, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "pool_id" character varying, CONSTRAINT "PK_9692808c54ea7250647b4af5efa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fea78beea061472f2449b28d97" ON "v2_pool_snapshot" ("pool_id") `)
        await db.query(`CREATE TABLE "v3_pool" ("id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "fee_tier" numeric NOT NULL, "dex" character varying(21) NOT NULL, "token0_id" character varying, "token1_id" character varying, CONSTRAINT "PK_691cdc021e19be68e3b4a3e9fdf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9ddf6f36e596c995fb72fb0bea" ON "v3_pool" ("token0_id") `)
        await db.query(`CREATE INDEX "IDX_08acf38106ac5d3d60a2ac5abf" ON "v3_pool" ("token1_id") `)
        await db.query(`CREATE TABLE "v3_pool_snapshot_tick" ("id" character varying NOT NULL, "tick_idx" numeric NOT NULL, "liquidity_gross" numeric NOT NULL, "liquidity_net" numeric NOT NULL, "pool_snapshot_id" character varying, CONSTRAINT "PK_86509e02dc5b6a53713aa50916a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_58dfed16de8d1e185e225bc9c5" ON "v3_pool_snapshot_tick" ("pool_snapshot_id") `)
        await db.query(`CREATE TABLE "v3_pool_snapshot" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "after_tx_id" text, "priority_inclusion_fee_per_unit" numeric, "index" integer, "fee" numeric, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "tick" integer, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "pool_id" character varying, CONSTRAINT "PK_0e812f286373482ad108ce7f1a1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_bdd9e25c06888b46aa13a34687" ON "v3_pool_snapshot" ("pool_id") `)
        await db.query(`CREATE TABLE "v4_pool" ("id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "fee_tier" numeric NOT NULL, "dex" character varying(21) NOT NULL, "token0_id" character varying, "token1_id" character varying, CONSTRAINT "PK_703efb032615374a7f2183247d3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1771caecd8eb8d78dfd8438325" ON "v4_pool" ("token0_id") `)
        await db.query(`CREATE INDEX "IDX_1f57cba185a620aab705037a9d" ON "v4_pool" ("token1_id") `)
        await db.query(`CREATE TABLE "v4_pool_snapshot_tick" ("id" character varying NOT NULL, "tick_idx" numeric NOT NULL, "liquidity_gross" numeric NOT NULL, "liquidity_net" numeric NOT NULL, "pool_snapshot_id" character varying, CONSTRAINT "PK_24e536360f41f3a5f462932e859" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ef05ff46c562aeec55afddb77a" ON "v4_pool_snapshot_tick" ("pool_snapshot_id") `)
        await db.query(`CREATE TABLE "v4_pool_snapshot" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "after_tx_id" text, "priority_inclusion_fee_per_unit" numeric, "index" integer, "fee" numeric, "plugin_fee" numeric, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "tick" integer, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "pool_id" character varying, CONSTRAINT "PK_78d3265508b38760d980a774d50" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9f91f0c4d3ead6889aefc654f2" ON "v4_pool_snapshot" ("pool_id") `)
        await db.query(`CREATE TABLE "stable_pool_coin" ("id" character varying NOT NULL, "index" integer NOT NULL, "pool_id" character varying, "token_id" character varying, CONSTRAINT "PK_9314cdf4c9c2ae6f8c6cc99e4c2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8b6d6eb33840664f55dd09ae6d" ON "stable_pool_coin" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_58fba0dc855e004ac835f9d2b5" ON "stable_pool_coin" ("token_id") `)
        await db.query(`CREATE TABLE "stable_pool" ("id" character varying NOT NULL, "created_at_block_number" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "dex" character varying(21) NOT NULL, "coin_count" integer NOT NULL, CONSTRAINT "PK_db2889f6510ef6c639ce8b38f15" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "stable_pool_snapshot_coin_balance" ("id" character varying NOT NULL, "balance" numeric NOT NULL, "pool_snapshot_id" character varying, "coin_id" character varying, CONSTRAINT "PK_966e254a77aae5f078ffae4179b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_deb16ad8f733a9b6ea38cac461" ON "stable_pool_snapshot_coin_balance" ("pool_snapshot_id") `)
        await db.query(`CREATE INDEX "IDX_bc7df55af49c071126e4fd097f" ON "stable_pool_snapshot_coin_balance" ("coin_id") `)
        await db.query(`CREATE TABLE "stable_pool_snapshot" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "after_tx_id" text, "index" integer, "priority_inclusion_fee_per_unit" numeric, "a" numeric NOT NULL, "initial_a" numeric NOT NULL, "future_a" numeric NOT NULL, "initial_a_time" numeric NOT NULL, "future_a_time" numeric NOT NULL, "fee" numeric NOT NULL, "virtual_price" numeric NOT NULL, "paused" boolean NOT NULL, "pool_id" character varying, CONSTRAINT "PK_7f092dcab182e5e7f7034b3ce74" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_9e2eb2e550026cff8179e03e97" ON "stable_pool_snapshot" ("pool_id") `)
        await db.query(`CREATE TABLE "st_dot_vault_snapshot" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "paused" boolean NOT NULL, "after_tx_id" text, "priority_inclusion_fee_per_unit" numeric, "index" integer, "total_dot" numeric NOT NULL, "total_st_dot" numeric NOT NULL, "exchange_rate" numeric NOT NULL, "fee" integer NOT NULL, "fee_treasury_bp" integer NOT NULL, "fee_developers_bp" integer NOT NULL, CONSTRAINT "PK_d6991069b53fb01de2bd4772ac8" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "v2_pool" ADD CONSTRAINT "FK_24bc7b055de2e69490450f40b2d" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v2_pool" ADD CONSTRAINT "FK_137cf1f2b23e63006ec88508afc" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v2_pool_snapshot" ADD CONSTRAINT "FK_fea78beea061472f2449b28d97c" FOREIGN KEY ("pool_id") REFERENCES "v2_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v3_pool" ADD CONSTRAINT "FK_9ddf6f36e596c995fb72fb0bea1" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v3_pool" ADD CONSTRAINT "FK_08acf38106ac5d3d60a2ac5abfc" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v3_pool_snapshot_tick" ADD CONSTRAINT "FK_58dfed16de8d1e185e225bc9c5f" FOREIGN KEY ("pool_snapshot_id") REFERENCES "v3_pool_snapshot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v3_pool_snapshot" ADD CONSTRAINT "FK_bdd9e25c06888b46aa13a34687d" FOREIGN KEY ("pool_id") REFERENCES "v3_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v4_pool" ADD CONSTRAINT "FK_1771caecd8eb8d78dfd8438325d" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v4_pool" ADD CONSTRAINT "FK_1f57cba185a620aab705037a9db" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v4_pool_snapshot_tick" ADD CONSTRAINT "FK_ef05ff46c562aeec55afddb77aa" FOREIGN KEY ("pool_snapshot_id") REFERENCES "v4_pool_snapshot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "v4_pool_snapshot" ADD CONSTRAINT "FK_9f91f0c4d3ead6889aefc654f2e" FOREIGN KEY ("pool_id") REFERENCES "v4_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stable_pool_coin" ADD CONSTRAINT "FK_8b6d6eb33840664f55dd09ae6db" FOREIGN KEY ("pool_id") REFERENCES "stable_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stable_pool_coin" ADD CONSTRAINT "FK_58fba0dc855e004ac835f9d2b5c" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stable_pool_snapshot_coin_balance" ADD CONSTRAINT "FK_deb16ad8f733a9b6ea38cac4616" FOREIGN KEY ("pool_snapshot_id") REFERENCES "stable_pool_snapshot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stable_pool_snapshot_coin_balance" ADD CONSTRAINT "FK_bc7df55af49c071126e4fd097fc" FOREIGN KEY ("coin_id") REFERENCES "stable_pool_coin"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stable_pool_snapshot" ADD CONSTRAINT "FK_9e2eb2e550026cff8179e03e97c" FOREIGN KEY ("pool_id") REFERENCES "stable_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP TABLE "v2_pool"`)
        await db.query(`DROP INDEX "public"."IDX_24bc7b055de2e69490450f40b2"`)
        await db.query(`DROP INDEX "public"."IDX_137cf1f2b23e63006ec88508af"`)
        await db.query(`DROP TABLE "v2_pool_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_fea78beea061472f2449b28d97"`)
        await db.query(`DROP TABLE "v3_pool"`)
        await db.query(`DROP INDEX "public"."IDX_9ddf6f36e596c995fb72fb0bea"`)
        await db.query(`DROP INDEX "public"."IDX_08acf38106ac5d3d60a2ac5abf"`)
        await db.query(`DROP TABLE "v3_pool_snapshot_tick"`)
        await db.query(`DROP INDEX "public"."IDX_58dfed16de8d1e185e225bc9c5"`)
        await db.query(`DROP TABLE "v3_pool_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_bdd9e25c06888b46aa13a34687"`)
        await db.query(`DROP TABLE "v4_pool"`)
        await db.query(`DROP INDEX "public"."IDX_1771caecd8eb8d78dfd8438325"`)
        await db.query(`DROP INDEX "public"."IDX_1f57cba185a620aab705037a9d"`)
        await db.query(`DROP TABLE "v4_pool_snapshot_tick"`)
        await db.query(`DROP INDEX "public"."IDX_ef05ff46c562aeec55afddb77a"`)
        await db.query(`DROP TABLE "v4_pool_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_9f91f0c4d3ead6889aefc654f2"`)
        await db.query(`DROP TABLE "stable_pool_coin"`)
        await db.query(`DROP INDEX "public"."IDX_8b6d6eb33840664f55dd09ae6d"`)
        await db.query(`DROP INDEX "public"."IDX_58fba0dc855e004ac835f9d2b5"`)
        await db.query(`DROP TABLE "stable_pool"`)
        await db.query(`DROP TABLE "stable_pool_snapshot_coin_balance"`)
        await db.query(`DROP INDEX "public"."IDX_deb16ad8f733a9b6ea38cac461"`)
        await db.query(`DROP INDEX "public"."IDX_bc7df55af49c071126e4fd097f"`)
        await db.query(`DROP TABLE "stable_pool_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_9e2eb2e550026cff8179e03e97"`)
        await db.query(`DROP TABLE "st_dot_vault_snapshot"`)
        await db.query(`ALTER TABLE "v2_pool" DROP CONSTRAINT "FK_24bc7b055de2e69490450f40b2d"`)
        await db.query(`ALTER TABLE "v2_pool" DROP CONSTRAINT "FK_137cf1f2b23e63006ec88508afc"`)
        await db.query(`ALTER TABLE "v2_pool_snapshot" DROP CONSTRAINT "FK_fea78beea061472f2449b28d97c"`)
        await db.query(`ALTER TABLE "v3_pool" DROP CONSTRAINT "FK_9ddf6f36e596c995fb72fb0bea1"`)
        await db.query(`ALTER TABLE "v3_pool" DROP CONSTRAINT "FK_08acf38106ac5d3d60a2ac5abfc"`)
        await db.query(`ALTER TABLE "v3_pool_snapshot_tick" DROP CONSTRAINT "FK_58dfed16de8d1e185e225bc9c5f"`)
        await db.query(`ALTER TABLE "v3_pool_snapshot" DROP CONSTRAINT "FK_bdd9e25c06888b46aa13a34687d"`)
        await db.query(`ALTER TABLE "v4_pool" DROP CONSTRAINT "FK_1771caecd8eb8d78dfd8438325d"`)
        await db.query(`ALTER TABLE "v4_pool" DROP CONSTRAINT "FK_1f57cba185a620aab705037a9db"`)
        await db.query(`ALTER TABLE "v4_pool_snapshot_tick" DROP CONSTRAINT "FK_ef05ff46c562aeec55afddb77aa"`)
        await db.query(`ALTER TABLE "v4_pool_snapshot" DROP CONSTRAINT "FK_9f91f0c4d3ead6889aefc654f2e"`)
        await db.query(`ALTER TABLE "stable_pool_coin" DROP CONSTRAINT "FK_8b6d6eb33840664f55dd09ae6db"`)
        await db.query(`ALTER TABLE "stable_pool_coin" DROP CONSTRAINT "FK_58fba0dc855e004ac835f9d2b5c"`)
        await db.query(`ALTER TABLE "stable_pool_snapshot_coin_balance" DROP CONSTRAINT "FK_deb16ad8f733a9b6ea38cac4616"`)
        await db.query(`ALTER TABLE "stable_pool_snapshot_coin_balance" DROP CONSTRAINT "FK_bc7df55af49c071126e4fd097fc"`)
        await db.query(`ALTER TABLE "stable_pool_snapshot" DROP CONSTRAINT "FK_9e2eb2e550026cff8179e03e97c"`)
    }
}
