
import { execSync } from 'child_process'
import * as dotenv from 'dotenv'
import * as fs from 'fs'
import * as path from 'path'

dotenv.config()

const SCHEMA_DIR = path.resolve(__dirname, '../schemas')
const COMMON_SCHEMA = path.join(SCHEMA_DIR, 'common.graphql')
const MERGED_SCHEMA = path.resolve(__dirname, '../../schema.graphql')

const PARACHAINS_DIR = path.resolve(__dirname, '../app/chains')
const DB_MIGRATIONS_DIR = path.resolve(__dirname, '../../db/migrations')

const JS_COMPILED_DIR = path.resolve(__dirname, '../../lib')

const GENERATED_HEADER = `# ==========================================================================
# AUTO-GENERATED FILE — do not edit manually.
# Generated by: npm run codegen:omni (src/scripts/generate-omni-model.ts)
# Source schemas: src/schemas/common.graphql + src/schemas/<chain>.graphql
# To regenerate: npm run codegen:omni
# ==========================================================================

`;

function mergeSchemas(common: string, parachain?: string): string {
    const parts: string[] = []
    parts.push(GENERATED_HEADER)
    parts.push(fs.readFileSync(common, 'utf8'))

    if (parachain) {
        const schemaPath = path.join(SCHEMA_DIR, `${parachain}.graphql`)
        if (!fs.existsSync(schemaPath))
            throw new Error(`Missing schema for ${parachain}`)

        parts.push(`\n# -------- ${parachain.toUpperCase()} ----------\n`)
        parts.push(fs.readFileSync(schemaPath, 'utf8'))
        parts.push(`\n# ------- END ${parachain.toUpperCase()} ----------\n`)
    } else {
        // Adds all parachains if no specific one is provided, to create the omni-model
        const others = fs.readdirSync(SCHEMA_DIR)
            .filter(f => f.endsWith('.graphql') && f !== 'common.graphql')

        for (const file of others) {
            parts.push(`\n# -------- ${file.toUpperCase()} ----------\n`)
            parts.push(fs.readFileSync(path.join(SCHEMA_DIR, file), 'utf8'))
            parts.push(`\n# ------- END ${file.toUpperCase()} ----------\n`)
        }
    }
    return parts.join('\n')
}

function runCodegen() {
    execSync('npx squid-typeorm-codegen', { stdio: 'inherit' })
}

function runCompileToJs(parachain: string) {
    fs.rmSync(JS_COMPILED_DIR, { recursive: true, force: true })
    fs.mkdirSync(JS_COMPILED_DIR, { recursive: true })

    execSync(`npx tsc -p tsconfig.${parachain}.json`, { stdio: 'inherit' })
}

function runMigration(parachain: string) {
    const dbPrefix = process.env.DB_URL_PREFIX || 'postgresql://localhost:5432/'
    process.env.DB_URL = dbPrefix + parachain

    const parachainMigrations = path.join(PARACHAINS_DIR, parachain, 'db/migrations')

    // Cleanup and prepare db/migrations
    fs.rmSync(DB_MIGRATIONS_DIR, { recursive: true, force: true })
    fs.mkdirSync(DB_MIGRATIONS_DIR, { recursive: true })

    // Copy chain-specific existing migrations into db/migrations
    if (fs.existsSync(parachainMigrations)) {
        for (const file of fs.readdirSync(parachainMigrations)) {
            fs.copyFileSync(
                path.join(parachainMigrations, file),
                path.join(DB_MIGRATIONS_DIR, file)
            )
        }
    }

    // Run migration in default dir
    try {

        execSync('npx squid-typeorm-migration generate', { stdio: 'inherit' })
        execSync('npx squid-typeorm-migration apply', { stdio: 'inherit' })
    } catch (e) {
        console.error('Migration failed — the database may have no pending changes:');
        // Cleanup temp db/migrations
        fs.rmSync(DB_MIGRATIONS_DIR, { recursive: true, force: true });
        return;
    }

    // Copy new/updated migrations back to parachain dir
    fs.rmSync(parachainMigrations, { recursive: true, force: true })
    fs.mkdirSync(parachainMigrations, { recursive: true })
    for (const file of fs.readdirSync(DB_MIGRATIONS_DIR)) {
        fs.copyFileSync(
            path.join(DB_MIGRATIONS_DIR, file),
            path.join(parachainMigrations, file)
        )
    }

    // Cleanup temp db/migrations
    fs.rmSync(DB_MIGRATIONS_DIR, { recursive: true, force: true })
}

// Loop through all parachains
const parachains = fs.readdirSync(SCHEMA_DIR)
    .filter(f => f.endsWith('.graphql') && f !== 'common.graphql')
    .map(f => path.basename(f, '.graphql'))

for (const chain of parachains) {
    console.log(`\n=== 🔁 Generating model + migration for ${chain} ===`)

    fs.writeFileSync(MERGED_SCHEMA, mergeSchemas(COMMON_SCHEMA, chain))

    runCodegen();
    runCompileToJs(chain);

    runMigration(chain)
}


console.log(`\n=== 🌐 Generating omni-model with all parachains ===`)

fs.writeFileSync(MERGED_SCHEMA, mergeSchemas(COMMON_SCHEMA))
runCodegen()

console.log(`✅ Omni model saved at src/common/model.ts`)

